### ISSUE TITLE
Incluir este código en aPlus

### ISSUE THREAD

**Issue by rtellezi** [daxslab/fotorecarga#1]
Hola:

Me gustaría usar este código en aPlus99 2.0, aplicación que desarrollo sin fines de lucro. Estaba planeando esta característica en la versión que estoy involucrado. Eso incluiría su nombre en los créditos, si está de acuerdo. Saludos.

**Comment by cccaballero** [comment]
Hola, no hay ningún inconveniente, el código esta liberado bajo los términos de la licencia MIT por lo que puede ser reutilizado en cualquier tipo de aplicación. Por lo demás encantados de poder contribuir con una aplicación tan popular como la suya. Saludos.

**Comment by yosbelms** [comment]
Y porque no se unen los dos y hacen una aplicación con las dos funcionalidades?

**Comment by rtellezi** [comment]
No es una mala idea, para mi sería lo ideal pues de todos modos obtendría el mismo resultado. Ahora mismo no tengo las herramientas para integrar este código en aPlus, espero que pronto.

**Comment by cccaballero** [comment]
Por nuestra parte no hay problema, escribenos a info at daxslab dot com (especifica quien eres porque la dirección es pública y recibimos bastantes mensajes ahí) para ponernos en contacto por correo y acordar como proceder.

Saludos.
